const axes=[
{id:'hpt',name:'Hypothalamic–Pituitary–Thyroid axis',short:'HPT axis and thyroid hormone feedback',prompt:'Sort the pathway that raises metabolic activity through thyroid hormone release.',tip:'Ask why the hypothalamus and anterior pituitary are upstream of the thyroid.',cards:[
{type:'stimulus',text:'Low circulating thyroid hormone or increased demand for metabolic activity'},
{type:'gland',text:'Hypothalamus and anterior pituitary activate the thyroid gland'},
{type:'hormone',text:'TRH and TSH drive release of T3 and T4'},
{type:'target',text:'Most body cells, especially tissues with high metabolic demand'},
{type:'response',text:'Metabolic rate and heat production increase'},
{type:'feedback',text:'Rising T3 and T4 reduce further TRH and TSH secretion'}],
followup:{q:'The thyroid gland fails to produce adequate T3 and T4. Which change is most consistent with the negative-feedback loop?',choices:['TSH decreases','TSH increases','TRH and TSH both decrease','Pituitary sensitivity to TRH disappears'],answer:1,explain:'Lower T3/T4 reduces negative feedback, so upstream TRH and TSH drive tends to rise.'}},
{id:'calcium',name:'Blood calcium regulation',short:'Parathyroid response to falling calcium',prompt:'Build the sequence that restores blood calcium when levels fall below normal.',tip:'Ask whether the response acts on bone, kidney, intestine, or all three.',cards:[
{type:'stimulus',text:'Blood calcium level decreases'},{type:'gland',text:'Parathyroid glands detect the drop in calcium'},{type:'hormone',text:'Parathyroid hormone (PTH) is released'},{type:'target',text:'Bone, kidneys, and indirectly the intestine'},{type:'response',text:'Calcium is conserved and added back to the blood'},{type:'feedback',text:'Normalized calcium suppresses additional PTH release'}],
followup:{q:'A patient has chronically low PTH secretion. Which immediate homeostatic problem is most likely?',choices:['Difficulty restoring low blood calcium','Persistent high blood glucose','Excess water reabsorption by the kidney','Excess thyroid hormone secretion'],answer:0,explain:'PTH is a major response to falling blood calcium, so inadequate PTH impairs restoration toward normal.'}},
{id:'hpa',name:'Hypothalamic–Pituitary–Adrenal cortex axis',short:'Cortisol pathway during prolonged stress',prompt:'Sort the pathway that supports longer-term stress adaptation through cortisol.',tip:'Contrast this with the faster sympathetic-adrenal medulla response.',cards:[
{type:'stimulus',text:'Persistent physiological stress or low blood glucose'},{type:'gland',text:'Hypothalamus and anterior pituitary stimulate the adrenal cortex'},{type:'hormone',text:'CRH and ACTH promote cortisol secretion'},{type:'target',text:'Liver, muscle, adipose tissue, and many other tissues'},{type:'response',text:'Blood glucose availability rises and stress resistance is maintained'},{type:'feedback',text:'Elevated cortisol inhibits CRH and ACTH release'}],
followup:{q:'A pituitary tumor secretes excess ACTH. What would you predict for cortisol?',choices:['Cortisol decreases','Cortisol increases','Cortisol is unchanged','Cortisol disappears only during stress'],answer:1,explain:'ACTH stimulates the adrenal cortex, so excessive ACTH drive tends to elevate cortisol.'}},
{id:'glucose',name:'Pancreatic glucose homeostasis',short:'Insulin response after a meal',prompt:'Arrange the endocrine events that lower blood glucose after carbohydrate intake.',tip:'Ask what glucagon would do under the opposite glucose condition.',cards:[
{type:'stimulus',text:'Blood glucose rises after a meal'},{type:'gland',text:'Pancreatic beta cells in the islets respond'},{type:'hormone',text:'Insulin is secreted'},{type:'target',text:'Liver, skeletal muscle, adipose tissue, and many body cells'},{type:'response',text:'Glucose uptake and storage increase, lowering blood glucose'},{type:'feedback',text:'As blood glucose returns toward normal, insulin secretion falls'}],
followup:{q:'Insulin is present, but target tissues respond poorly to it. Which step of the pathway is primarily impaired?',choices:['Stimulus detection','Hormone production','Target responsiveness','Negative feedback sensing only'],answer:2,explain:'The hormone is present, but its target tissues have reduced responsiveness, so the defect is at the target-response step.'}},
{id:'adh',name:'Posterior pituitary water balance',short:'ADH pathway during dehydration',prompt:'Sort the pathway that conserves body water when osmolarity rises.',tip:'Reinforce hypothalamic production versus posterior pituitary release of ADH.',cards:[
{type:'stimulus',text:'Dehydration increases blood osmolarity or decreases blood volume'},{type:'gland',text:'Hypothalamic neurons signal the posterior pituitary'},{type:'hormone',text:'Antidiuretic hormone (ADH) is released'},{type:'target',text:'Kidney tubules and collecting ducts'},{type:'response',text:'Water reabsorption increases and urine volume falls'},{type:'feedback',text:'Improved fluid balance reduces the ADH stimulus'}],
followup:{q:'ADH release is absent during dehydration. Which change is most likely?',choices:['Urine volume falls','Urine volume rises','Blood glucose rapidly falls','PTH secretion stops'],answer:1,explain:'Without ADH, collecting ducts conserve less water, so urine volume rises rather than falling.'}},
{id:'stress',name:'Acute sympathetic–adrenal medulla response',short:'Fast endocrine support during alarm stage',prompt:'Build the pathway that produces a rapid fight-or-flight endocrine response.',tip:'Use this axis to distinguish neural triggering from classic hypothalamic-pituitary loops.',cards:[
{type:'stimulus',text:'Acute threat, fear, or sudden physiological alarm'},{type:'gland',text:'Sympathetic input stimulates the adrenal medulla'},{type:'hormone',text:'Epinephrine and norepinephrine are released'},{type:'target',text:'Heart, blood vessels, liver, lungs, and skeletal muscle'},{type:'response',text:'Cardiac output, blood flow to muscle, and fuel mobilization increase'},{type:'feedback',text:'As the threat passes, sympathetic drive declines'}],
followup:{q:'Which feature best distinguishes this pathway from the HPA axis?',choices:['It uses a hormone','It includes target tissues','It begins with rapid sympathetic neural input','It contributes to stress physiology'],answer:2,explain:'The acute adrenal-medulla response is initiated directly by sympathetic neural input and is faster than the HPA endocrine cascade.'}}
];
const slots=[
{key:'stimulus',label:'Stimulus',clue:'What change starts the pathway?'},{key:'gland',label:'Gland / source',clue:'Which endocrine structure responds?'},{key:'hormone',label:'Hormone',clue:'What messenger is released?'},{key:'target',label:'Target',clue:'Which tissue receives the signal?'},{key:'response',label:'Response',clue:'What physiological effect follows?'},{key:'feedback',label:'Feedback',clue:'How does the system taper the signal?'}];
let state={axisIndex:0,cards:[],selected:null,placements:{},attempts:0,level:'guided',mystery:false,lastResults:null};
let mastery=JSON.parse(localStorage.getItem('endocrineAxisMasteryV2')||'{}');
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loadAxis(i,mystery=false){state.axisIndex=i;state.mystery=mystery;state.attempts=0;state.selected=null;state.placements={};state.lastResults=null;state.cards=shuffle(axes[i].cards.map((c,n)=>({...c,id:axes[i].id+'-'+n})));$('followup').classList.remove('show');$('followupFeedback').textContent='';renderAll()}
function renderAll(){renderAxisList();const a=axes[state.axisIndex];$('axisTitle').textContent=state.mystery?'Mystery Axis':a.name;$('axisSubtitle').textContent=state.mystery?'Identify the pathway from the physiology, then build it.':a.short;$('promptText').textContent=a.prompt;$('teachingTip').textContent='Instructor tip: '+a.tip;$('attemptCount').textContent=state.attempts;renderBins(state.lastResults||{});renderCards();updateStats();updateMastery();updateLevelUI();$('feedbackBox').innerHTML='Select a card, then select the slot where it belongs.'}
function renderAxisList(){const el=$('axisList');el.innerHTML='';axes.forEach((a,i)=>{const b=document.createElement('button');b.className='axis'+(i===state.axisIndex&&!state.mystery?' active':'')+(mastery[a.id]?' complete':'');b.innerHTML=`<strong>${a.name}</strong><span>${a.short}</span>`;b.onclick=()=>loadAxis(i,false);el.appendChild(b)})}
function renderBins(results={}){const el=$('bins');el.innerHTML='';slots.forEach((s,idx)=>{const id=state.placements[s.key],card=state.cards.find(c=>c.id===id),sec=document.createElement('section');const hidden=state.level!=='guided';sec.className='bin'+(hidden?' hidden-label':'')+(results[s.key]===true?' correct':results[s.key]===false?' incorrect':'');const title=hidden?`Step ${idx+1}`:s.label;const clue=hidden?'':s.clue;sec.innerHTML=`<h3><span>${title}</span><small>${clue}</small></h3>`;if(card){let b=document.createElement('button');b.className='card';b.innerHTML=`${state.level==='guided'?`<span class="tag ${card.type}">${card.type}</span>`:''}<div>${card.text}</div>`;b.onclick=e=>{e.stopPropagation();delete state.placements[s.key];state.lastResults=null;renderBins();renderCards();updateStats()};sec.appendChild(b)}sec.onclick=()=>placeSelected(s.key);el.appendChild(sec)})}
function renderCards(){const el=$('cards');el.innerHTML='';const un=state.cards.filter(c=>!Object.values(state.placements).includes(c.id));un.forEach(c=>{let b=document.createElement('button');b.className='card'+(state.selected===c.id?' selected':'');b.innerHTML=`${state.level==='guided'?`<span class="tag ${c.type}">${c.type}</span>`:''}<div>${c.text}</div>`;b.onclick=()=>{state.selected=state.selected===c.id?null:c.id;renderCards()};el.appendChild(b)});if(!un.length){let d=document.createElement('div');d.className='card';d.textContent='All cards placed. Check the sequence or remove a card to revise.';el.appendChild(d)}}
function placeSelected(key){if(!state.selected)return;for(const k of Object.keys(state.placements))if(state.placements[k]===state.selected)delete state.placements[k];state.placements[key]=state.selected;state.selected=null;state.lastResults=null;renderBins();renderCards();updateStats()}
function updateStats(){const placed=Object.keys(state.placements).length;$('placementStatLabel').textContent=state.lastResults?'Placed correctly':'Cards placed';if(state.lastResults){let correct=Object.values(state.lastResults).filter(Boolean).length;$('placementStat').textContent=`${correct} / 6`}else $('placementStat').textContent=`${placed} / 6`;$('axisStatus').textContent=mastery[axes[state.axisIndex].id]?'Mastered':'Not yet'}
function checkSequence(){state.attempts++;$('attemptCount').textContent=state.attempts;let missing=0,correct=0,res={};slots.forEach(s=>{const c=state.cards.find(x=>x.id===state.placements[s.key]);if(!c){missing++;return}res[s.key]=c.type===s.key;if(res[s.key])correct++});if(missing){$('feedbackBox').innerHTML=`You still have <strong>${missing}</strong> empty slot${missing>1?'s':''}. Complete the pathway first.`;return}state.lastResults=res;renderBins(res);updateStats();if(correct===6){mastery[axes[state.axisIndex].id]=true;localStorage.setItem('endocrineAxisMasteryV2',JSON.stringify(mastery));updateMastery();renderAxisList();$('axisStatus').textContent='Mastered';$('feedbackBox').innerHTML=`<strong>Complete.</strong> All six steps are correct.${state.mystery?` You built the <strong>${axes[state.axisIndex].name}</strong>.`:''}`;if(state.level==='predict')showFollowup()}else{const wrong=slots.filter(s=>res[s.key]===false).map(s=>s.label);$('feedbackBox').innerHTML=state.level==='guided'?`<strong>${correct} of 6 correct.</strong> Revisit: ${wrong.join(', ')}.`:`<strong>${correct} of 6 correct.</strong> ${6-correct} step${6-correct===1?' needs':'s need'} revision.`}}
function showFollowup(){const f=axes[state.axisIndex].followup;$('followupQuestion').textContent=f.q;const c=$('followupChoices');c.innerHTML='';f.choices.forEach((txt,i)=>{let b=document.createElement('button');b.className='choice';b.textContent=txt;b.onclick=()=>{[...c.children].forEach(x=>x.disabled=true);b.classList.add(i===f.answer?'correct':'incorrect');if(i!==f.answer)c.children[f.answer].classList.add('correct');$('followupFeedback').textContent=(i===f.answer?'Correct. ':'Not quite. ')+f.explain};c.appendChild(b)});$('followup').classList.add('show')}
function updateMastery(){const n=axes.filter(a=>mastery[a.id]).length;$('masteryText').textContent=`${n} of ${axes.length} mastered`;$('heroMastery').textContent=`${n} / ${axes.length}`;$('masteryFill').style.width=`${(n/axes.length)*100}%`}
function updateLevelUI(){const map={guided:['Level 1: Guided Sort','Card roles and slot labels are visible. Build the six-step physiological story.','Guided'],challenge:['Level 2: Build the Pathway','Role labels are hidden. Determine the sequence from the physiology alone.','Challenge'],predict:['Level 3: Predict the Disorder','Build the unlabeled pathway, then answer a perturbation question.','Predict']};$('levelName').textContent=map[state.level][0];$('levelDescription').textContent=map[state.level][1];$('levelStat').textContent=map[state.level][2]}
$('checkBtn').onclick=checkSequence;$('shuffleBtn').onclick=()=>loadAxis(state.axisIndex,state.mystery);$('resetBtn').onclick=()=>loadAxis(state.axisIndex,state.mystery);$('mysteryBtn').onclick=()=>loadAxis(Math.floor(Math.random()*axes.length),true);$('levelSelect').onchange=e=>{state.level=e.target.value;state.lastResults=null;$('followup').classList.remove('show');renderBins();renderCards();updateStats();updateLevelUI();$('feedbackBox').textContent='Learning level changed. Build the pathway from the beginning or continue your current arrangement.'};
let instructor=false;$('studentInstructorBtn').onclick=()=>{instructor=!instructor;document.querySelectorAll('.instructor-only').forEach(x=>x.classList.toggle('hide',!instructor));$('studentInstructorBtn').textContent=instructor?'Instructor view':'Student view'};
$('themeBtn').onclick=()=>{const r=document.documentElement;r.dataset.theme=r.dataset.theme==='dark'?'light':'dark'};
if(matchMedia('(prefers-color-scheme:dark)').matches)document.documentElement.dataset.theme='dark';
loadAxis(0);
